---
- name: Log Cleanup via Templated Script
  hosts: local
  vars_files:
    - vars/vars.yml
  tasks:

    - name: Ensure log directory exists
      file:
        path: "{{ log_directory }}"
        state: directory
        mode: '0755'

    - name: Generate cleanup script from template
      template:
        src: templates/cleanup.sh.j2
        dest: "{{ cleanup_script_path }}"
        mode: '0755'

    - name: Execute the cleanup script
      command: bash "{{ cleanup_script_path }}"
      register: cleanup_output

    - name: Show script output
      debug:
        var: cleanup_output.stdout

