---
- name: Log Cleanup Using Templated Script
  hosts: local
  become: true
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Ensure log directory exists
      file:
        path: "{{ log_directory }}"
        state: directory
        mode: '0755'

    - name: Deploy cleanup script from template
      template:
        src: templates/cleanup_logs.sh.j2
        dest: "{{ cleanup_script_path }}"
        mode: '0755'

    - name: Execute cleanup script
      command: "{{ cleanup_script_path }}"
      register: script_output

    - name: Show script output
      debug:
        msg: "{{ script_output.stdout_lines }}"

