---
- name: Log Cleanup via Templated Script
  hosts: log_hosts
  vars_files:
    - vars.yml
  become: yes

  tasks:

    - name: Ensure the log directory exists
      file:
        path: "{{ log_cleanup_path }}"
        state: directory
        mode: '0755'

    - name: Generate log cleanup script from template
      template:
        src: "templates/cleanup_logs.sh.j2"
        dest: "{{ cleanup_script_path }}"
        mode: '0755'

    - name: Execute the log cleanup script
      command: "{{ cleanup_script_path }}"
      register: cleanup_output

    - name: Display script output
      debug:
        var: cleanup_output.stdout_lines
